### PR TITLE
Move /pages into /user

### LINKED ISSUE #1582: Move `/pages` into `/user`
Directory `/pages` contains user stuff, it belongs to `/user` : move it there

This should be automated during update if possible:
- check write permission & create directory, copy files there
- attempt to delete `/pages` (should fail most of the times)
- display notice explaining what's left to do for the user with a link to the wiki

Wiki document : 
- explain what to do
- explain why it's better (all user & install dependant stuff regrouped into one directory)

### PR DESCRIPTION
**Pull request by ozh**
Let's close #1582 

* [x] move and update functions
* [x] add tests
* [x] create docs for pages
* [x] create doc for migration (manual or with a plugin)

### CODE REVIEW

**Comment by ozh** [comment]
@LeoColomb any comment ? Documentation is here: https://github.com/YOURLS/YOURLS/wiki/Pages

File: includes/functions-html.php [hunk 1]
```diff
@@ -855,18 +855,22 @@ function yourls_notice_box( $message, $style = 'notice' ) {
...
+ *
+ *  @since 1.0
+ *  @param $page      PHP file to display
  */
 function yourls_page( $page ) {
-	$include = YOURLS_ABSPATH . "/pages/$page.php";
+	$include = YOURLS_PAGEDIR . "/$page.php";
 	if( !file_exists( $include ) ) {
-		yourls_die( "Page '$page' not found", 'Not found', 404 );
+		yourls_die( yourls_s('Page "%1$s" not found', $page), yourls__('Not found'), 404 );
```
Comment (LeoColomb) [inline includes/functions-html.php:869]: 👍

**Comment by ozh** [comment]
@LeoColomb "index.html file are no more relevant, not to say completely useless now." what has changed?
